NUProjectDemo/Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NUProjectDemo.Models;

namespace NUProjectDemo.Controllers
{
    public class MovieController : Controller
    {
        List<Movie> movies = new List<Models.Movie>();
        // GET: MovieController
        public ActionResult Index()
        {
            
            Movie a = new Movie() { Id = 1,Price=100.00M };
            Movie b = new Movie() { Id = 2, Price = 150.00M, Title="LOTR" };

            movies.Add(a);
            movies.Add(b);

            

            return View(movies);
        }

        // GET: MovieController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MovieController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MovieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MovieController/Edit/5
        public ActionResult Edit(int id)
        {
            Movie a = new Movie() { Id = 1, Price = 100.00M };
            Movie b = new Movie() { Id = 2, Price = 150.00M, Title = "LOTR" };

            movies.Add(a);
            movies.Add(b);
            Movie movie = movies.FirstOrDefault(x => x.Id == id);
            return View(movie);
        }

        // POST: MovieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MovieController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MovieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NUProjectDemo/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NUProjectDemo.Data;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Borders;
using iText.Layout.Element;

namespace NUProjectDemo.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
           
            
        }
  
        // GET: ProductController
        public async Task<IActionResult> Index()
        {
            //check if the user is logged in via session variable _Name
            try
            {
                var u = HttpContext.Session.GetString("_Name");
                if (u == null)
                {
                    return View("../UserLogin/Index");
                }
            }
            catch (Exception ex)
            {
                return View("../UserLogin/Index");
            }
            return View(await _context.Products.ToListAsync());
        }

        public ActionResult Index2()
        {
            return View(_context.Products.ToList());
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }
            var p = _context.Products.Find(id);
            if (p == null)
            {
                return NotFound();
            }
            return View(p);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            //check if the user is logged in via session variable _Name
            try
            {
                var u = HttpContext.Session.GetString("_Name");
                if (u == null)
                {
                    return View("../UserLogin/Index");
                }
            }
            catch (Exception ex)
            {
                return View("../UserLogin/Index");
            }
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        public ActionResult Create([Bind()] Models.Products product)
        {
          
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(product); //preparing the SQL statement for add
                    _context.SaveChanges(); //responsible for executing the add sql
                    return RedirectToAction(nameof(Index)); // return View("Index");
                }
                catch
                {
                    return View();
                }
            }
            return View(product);
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            //check if the user is logged in via session variable _Name
            try
            {
                var u = HttpContext.Session.GetString("_Name");
                if (u == null)
                {
                    return View("../UserLogin/Index");
                }
            }
            catch (Exception ex)
            {
                return View("../UserLogin/Index");
            }
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }
            var p = _context.Products.Find(id);
            if (p == null)
            {
                return NotFound();
            }
            return View(p);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Models.Products p = new Models.Products();
                p.idproducts = int.Parse(collection["idproducts"]);
                p.productname = collection["productname"];
                p.datetimeadded = DateTime.Parse(collection["datetimeadded"]);
                p.category = collection["category"];
                p.price = double.Parse(collection["price"]);
                p.description = collection["description"];

                _context.Update(p);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        //public ActionResult Edit(int id, [Bind()]Models.Products product)
        //{
        //    if (id != product.idproducts)
        //    {
        //        return View("InvalidAction");

        //    }
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(product); //preparing the SQL statement for update
        //            _context.SaveChanges(); //responsible for executint eh update
        //            return RedirectToAction(nameof(Index)); // return View("Index");
        //        }
        //        catch
        //        {
        //            return View();
        //        }
        //    }
        //    return View(product);
        //}

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }
            var p = _context.Products.Find(id);
            if (p == null)
            {
                return NotFound();
            }
            return View(p);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, [Bind()] Models.Products product)
        {
            {
                if (id != product.idproducts)
                {
                    return View("InvalidAction");

                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Remove(product); //preparing the SQL statement for delete
                        _context.SaveChanges(); //responsible for executing the delete
                        return RedirectToAction(nameof(Index)); // return View("Index");
                    }
                    catch
                    {
                        return View();
                    }
                }
                return View(product);
            }
        }

        public ActionResult PrintAll()
        {
            byte[] pdfBytes = null;
            using(var stream = new MemoryStream())
            using(var wri = new PdfWriter(stream))
            using (var pdf = new PdfDocument(wri))
            using(var document = new Document(pdf, iText.Kernel.Geom.PageSize.A4.Rotate(),false))
            {
                document.Add(new Paragraph("This is a test")); //this is how to add a text to pdf

                //to add a table
                Table table = new Table(2,false);
                Cell h1 = new Cell()
                    .SetTextAlignment(iText.Layout.Properties.TextAlignment.CENTER)
                    .Add(new Paragraph("ID"))
                    .SetBold();
                table.AddCell(h1);
                Cell h2 = new Cell()
                    .SetTextAlignment(iText.Layout.Properties.TextAlignment.CENTER)
                    .Add(new Paragraph("Product Name"))
                    .SetBold();
                table.AddCell(h2);

                foreach(var i in _context.Products)
                {
                    Cell idvalue = new Cell()
                        .SetTextAlignment(iText.Layout.Properties.TextAlignment.LEFT)
                        .Add(new Paragraph(i.idproducts.ToString()));
                    Cell productname = new Cell()
                        .SetTextAlignment(iText.Layout.Properties.TextAlignment.LEFT)
                        .Add(new Paragraph(i.productname.ToString()));
                    table.AddCell(idvalue);
                    table.AddCell(productname);

                    //set a border
                    Border b = new SolidBorder(1.0f);
                    table.SetBorderBottom(b);
                    document.Add(table);
                }
                document.Close();
                document.Flush();
                pdfBytes = stream.ToArray();
            }
            //download
            var filename = "ProductsList" + DateTime.Now.ToString() + ".pdf";
            HttpContext.Response.Headers.Add("content-disposition", "inline;filename=" + filename); //you can automate the "sample.pdf" to change to other filename
            return File(fileContents: pdfBytes, "application/pdf");
        }

        public ActionResult PrintId(int id)
        {
            byte[] pdfBytes = null;
            using (var stream = new MemoryStream())
            using (var wri = new PdfWriter(stream))
            using (var pdf = new PdfDocument(wri))
            using (var document = new Document(pdf, iText.Kernel.Geom.PageSize.A4.Rotate(), false))
            {
                document.Add(new Paragraph("This is a test")); //this is how to add a text to pdf

                //to add a table
                Table table = new Table(2, false);
                Cell h1 = new Cell()
                    .SetTextAlignment(iText.Layout.Properties.TextAlignment.CENTER)
                    .Add(new Paragraph("ID"))
                    .SetBold();
                table.AddCell(h1);
                Cell h2 = new Cell()

NUProjectDemo/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace NUProjectDemo.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            int status = 0; //0 for maintenance, 1 for ok status
            ViewData["Message"] = "This handles all student concerns in NU. You must have an account to access the other modules.";
            if (status == 0)
            {
                return View("Views/ErrorCollection/Maintenance.cshtml");
            }
            else
            {
                return View("Views/Home/Privacy.cshtml");
            }
            return View();
        }
        // GET: /HelloWorld/Welcome/ 
        // Requires using System.Text.Encodings.Web;
        public IActionResult Welcome(string name, int numTimes = 1)
        {
            ViewData["Message"] = "Hello " + name;
            ViewData["NumTimes"] = numTimes;

            return View();
        }
    }
    
}

NUProjectDemo/Controllers/UserLoginController.cs
using Microsoft.AspNetCore.Mvc;
using NUProjectDemo.Models;
using NUProjectDemo.Data;

namespace NUProjectDemo.Controllers
{
    public class UserLoginController : Controller
    {
        public const string LogoutMessage = "You have been logged out";
        public const string SessionKeyName = "_Name";
        private readonly ApplicationDbContext _context;

        public UserLoginController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// This is to display the login page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

    
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Signup(User u)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(u); //preparing the SQL statement for add
                    _context.SaveChanges(); //responsible for executing the add sql
                    return RedirectToAction(nameof(Index)); // return View("Index");
                }
                catch
                {
                    return View();
                }
                return View();
            }
            return View(u);
        }

        public IActionResult Authenticate(Login u)
        {
            if (u != null)
            {
                if (ModelState.IsValid)
                {
                    var account = from m in _context.Users select m;
                    account = account.Where(s => s.email.Contains(u.email));
                    //select * from users where email = u.email
                    if (account.Count() != 0)
                    {
                        if(account.First().password == u.password)
                        {
                            //set the session
                            HttpContext.Session.SetString(SessionKeyName, u.email);
                            return View("../Home/Index");
                        }
                    }
                    else
                    {
                        return View("Invalid");
                    }
                }
            }
            return View("Invalid");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return View("Index");
        }
    }
}

NUProjectDemo/Views/Shared/InvalidAction.cshtml
Invalid action

NUProjectDemo/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NUProjectDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NUProjectDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NUProjectDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            var u = @Accessor.HttpContext.Session.GetString("_Name");
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student's Section</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>*@
                        @{
                            if(u!=null){
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                </li>
                                <li class="nav-item">
                                    Welcome @u
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserLogin" asp-action="Logout">Logout</a>
                                </li>
                            }else{
                                <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="UserLogin" asp-action="Index">Login</a>
                                 </li>
                                 <li class="nav-item">
                                      <a class="nav-link text-dark" asp-area="" asp-controller="UserLogin" asp-action="Register">Register</a>
                                 </li>
                            }
                        }
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NUProjectDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>